### ISSUE TITLE
Add support for node-js  v18

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#183]
As it currently fails the CI tests

**Comment by hoffmannjan** [comment]
@gyroflaw would prefer to use Dockerized NCTL because it fixes the issue. We need to wait for @TomVasile to discuss this.

**Comment by hoffmannjan** [comment]
Please update outdated libraries here and check if everything is working correctly. If this is a problem that happens only on CI let me know.

**Comment by gyroflaw** [comment]
we can fix this issue by migrating current node ci script to using [this library](https://github.com/gyroflaw/casper-node-launcher)

**Comment by gyroflaw** [comment]
we can fix this issue by migrating current node ci script to using [this library](https://github.com/gyroflaw/casper-node-launcher)
