### ISSUE TITLE
[Feature Request] Support configurable timeout for requests

### ISSUE THREAD

**Issue by cy-cdc** [casper-ecosystem/casper-client-sdk#199]
Hi, I notice that the implementation of the Transport class ultimately supports passing in a [request timeout value as a parameter](https://github.com/casper-ecosystem/casper-js-sdk/blob/673b176276960d740355f62462b736b71fc4306f/src/services/ProviderTransport.ts#L52). 
However, this does not seem to be exposed any where in the options to allow us to configure this value. Would be nice to have this, cheers!

**Comment by gyroflaw** [comment]
@cy-cdc , could you please share the code snippet you're using?
