### ISSUE TITLE
Add support to validate checksums in the mixed-case hex representation of public keys

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#200]
It's a feature supported by node, but not by the SDK.
SDK should be able to properly validate mixed-case publickeys.

**Comment by RitaMAllenCA** [comment]
Possibly pair programming with Ryo

**Comment by RitaMAllenCA** [comment]
@gyroflaw please assign Jan as a reviewer of this PR.  Thanks
