### ISSUE TITLE
SDK only works from server side calls

### ISSUE THREAD

**Issue by Levike34** [casper-ecosystem/casper-client-sdk#221]
**Describe the bug**
This SDK will fail from client side calls with CORS errors.

**Expected behavior**
It should run from client side calls.

**Additional context**
In my Next.js app, Casper js sdk functions only work if called from getServerSideProps() or from /pages/api routes.

**Comment by KillianH** [comment]
That's because you need to have a node endpoint that authorize CORS. It's not a SDK bug.

**Comment by Levike34** [comment]
For anyone experiencing this problem, changing the localhost port to 8080 has solved the issue for me.

**Comment by hoffmannjan** [comment]
Ok, thanks @Levike34 so we're closing this issue.
