### ISSUE TITLE
[Bug] Doc github page isn't updated

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-client-sdk#227]
The doc website isn't updated. Looks like it's the case since march 2022 the doc points to this commit https://github.com/casper-ecosystem/casper-js-sdk/commits/7da7c50

**Comment by hoffmannjan** [comment]
That's true, I'm currently working on fixing this and adding inline docs to the README :)

**Comment by RitaMAllenCA** [comment]
@hoffmannjan Will you do this as part of the current sprint? NVMD - I see the inline docs ticket.  I'll put the inline docs issue in the next release.

**Comment by RitaMAllenCA** [comment]
It's not blocked, but will be N/A after https://app.zenhub.com/workspaces/engineering-l2-62618a6423afe100128e4656/issues/gh/casper-ecosystem/casper-js-sdk/165 is complete

**Comment by gyroflaw** [comment]
close this issue in favor of https://github.com/casper-ecosystem/casper-js-sdk/issues/259
