### ISSUE TITLE
Fix nightly tests issue (1.5 dependent)

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#231]
So in @TomVasile [PR](https://github.com/casper-ecosystem/casper-js-sdk/pull/229) there is a fix, but still a few tests are failing. So we need to check and try to fix the issue.

Can't mark the dependency in zenhub but once this PR merges we can merge this one: https://github.com/casper-network/casper-node/issues/3583

**Comment by RitaMAllenCA** [comment]
possible issue with 1.5node that will have to be addressed and dependent on that fix.  Pending an update from Fraser

**Comment by RitaMAllenCA** [comment]
dependent on this change in 1.5 https://github.com/casper-network/casper-node/issues/3583
