### ISSUE TITLE
SPIKE: Research alternative solutions for PR 248

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-client-sdk#250]
https://github.com/casper-ecosystem/casper-js-sdk/pull/248

The fix in this PR requires the use of 2 deprecated packages, which we prefer not to do.  Please take the next 2 days to research options.  If no better option is available, confirm with @hoffmannjan for merge approval.

**Comment by gyroflaw** [comment]
Created a [PR ](https://github.com/ozum/concat-md/pull/31) on original library which fix vulnerabilities.

**Comment by hoffmannjan** [comment]
Can be closed as @gyroflaw found a solution :)
