### ISSUE TITLE
SPIKE: Research is it possible to force HTTP 1.1 for EventStream in a browser

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#257]
So currently when using EventStream it crashes as because of the `http2` dependency. Please check if:

- it is possible to support http2 in a browser (I don't see any polyfills)
- it is possible to force `http 1.1 + ssl` in a browser

Because when calling `curl -vso /dev/null --http2 'https://events.mainnet.casperlabs.io/events/main'` I see that both `http 1.1` and `http2` is supported:

```
~ → curl -vso /dev/null --http2 'https://events.mainnet.casperlabs.io/events/main'
*   Trying 3.134.238.5:443...
* Connected to events.mainnet.casperlabs.io (3.134.238.5) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
```

**Comment by RitaMAllenCA** [comment]
@gyroflaw If this can not be fixed, we need to revert the change and get a more sustained fix.

**Comment by gyroflaw** [comment]
> ALPN: offers http/1.1

```
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.mainnet.casperlabs.io
*  start date: Feb 10 00:00:00 2023 GMT
*  expire date: Jan 30 23:59:59 2024 GMT
*  subjectAltName: host "events.mainnet.casperlabs.io" matched cert's "*.mainnet.casperlabs.io"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
```
It seems that this load balancer using HTTP2

> *Using HTTP2, server supports multiplexing
> *Connection state changed (HTTP/2 confirmed)

**Comment by gyroflaw** [comment]
And consider this module: https://github.com/davedoesdev/browser-http2-duplex can be used in our SDK

**Comment by gyroflaw** [comment]
Currently the eventstream ALB supports http1.1 protocol.
