### ISSUE TITLE
Add tests to check if SDK works properly in browser

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#258]
So we won't need to manually test every release in a browser environment we should prepare a set of tests checking the core functionalities in a browser environment.

**Comment by gyroflaw** [comment]
### Workaround:
- https://github.com/tom-sherman/blog/blob/main/posts/02-running-jest-tests-in-a-browser.md
- https://blog.chainsafe.io/test-your-typescript-code-with-karma-and-jest-9554f99593e4

### Frameworks:
- https://github.com/karma-runner/karma
- https://github.com/jasmine/jasmine

### Adapters
- https://github.com/karma-runner/karma-jasmine

FYI: @hoffmannjan
