### ISSUE TITLE
GitHub Pages examples directory link does not work

### ISSUE THREAD

**Issue by cryofracture** [casper-ecosystem/casper-client-sdk#275]
**Describe the bug**
The new GitHub Pages home of examples with release version 2.12.0 directs to a page that does not exist.

**Steps To Reproduce**

Identify if any Prequisites:

1. Navigate to [GitHub pages URL](https://casper-ecosystem.github.io/casper-js-sdk/) or the [Main Repository link](https://github.com/casper-ecosystem/casper-js-sdk)
2.  Link on bottom of page says: "Basic examples of library usage are stored inside [/test](https://github.com/casper-ecosystem/casper-js-sdk/tree/dev/test) directory."
3. Link returns 404 Error

**Expected behavior**
Link should provide users with new code examples.

**Defect Type**
- [ ] Regression
- [ x ] New
- [ ] Escape

**Comment by hoffmannjan** [comment]
@RitaMAllenCA this is meant to be part of `2.12.1`

**Comment by gyroflaw** [comment]
Fixed in https://github.com/casper-ecosystem/casper-js-sdk/pull/277
