### ISSUE TITLE
Create a new npm library that makes easy to setup a single node for testing

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#291]

**Comment by gyroflaw** [comment]
ref https://github.com/lirantal/nodejs-cli-apps-best-practices

**Comment by gyroflaw** [comment]
Implemented in https://github.com/gyroflaw/casper-node-launcher

**Comment by hoffmannjan** [comment]
Hi Ryo,

- we will need to move it to repo in our organization
- we will need to make it work on Linux & Mac (currently I wasn't able to run on Mac)

**Comment by gyroflaw** [comment]
> we will need to make it work on Linux & Mac (currently I wasn't able to run on Mac)
I check this with Rob and he said that Mac isn't currently supported, you should use Docker to use it

**Comment by gyroflaw** [comment]
updated repo https://github.com/casper-network/casper-node-launcher-js
