### ISSUE TITLE
Add a switch to set checksummed/non-checksummed mode

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#294]
So by default the SDK will run in `legacyMode` that will work with non-checksummed publickeys and hashes. 
It will be possible to switch to  `newMode` which will operate on checksummed values. 

`README.md` should be updated as well as we can add some npm deprecation message about the changes.

**Comment by KillianH** [comment]
This is concerning. That's the second rollback on the checksum feature. Why that change since checksum is by default in 2.11 ?

**Comment by RitaMAllenCA** [comment]
will address in 2.14

**Comment by hoffmannjan** [comment]
As @KillianH  mentioned - it requires only adding one parameter [here](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/CLValue/PublicKey.ts#L120-L128) and call `toHex(false)` to prevent any compatibility breaks. Closing as won't do.
