### ISSUE TITLE
Cannot Build CLKey from Contract Hash

### ISSUE THREAD

**Issue by dylanireland** [casper-ecosystem/casper-client-sdk#327]
Using the [casper-client](https://github.com/casper-ecosystem/casper-client-rs), it is possible to give any hash value the type `key`, but the Casper JS SDK lacks the ability to build a `CLKey` object from any given hash.

For example, on [line 7 in this shell script](https://github.com/dylanireland/dApp-dev-series-7/blob/main/deposit.sh#L7), a `key` argument is defined with the value "hash-b62481085812c4f56027f5fb7f3e5e2f087b14190da8762fb88889e4945178be".
This works properly. [Here is a successful deploy](https://testnet.cspr.live/deploy/d5bb2f550c378983357e159c8aa7296054b04cd266605562f1aad1c99313fc3d) as an example (expand the raw data and look under the first argument `contract_hash`).

Using the Casper JS SDK, however, it appears this cannot be done. 

Traditionally, building a `CLKey` object is done by calling `CLValueBuilder.key()`, which accepts a parameter of type `CLKeyParameters`, which is any of the following types:

* CLByteArray
* CLURef
* CLAccountHash
* CLPublicKey

*Reference: [CLKey](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/CLValue/Key.ts#L130), [CLValueBuilder.key](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/CLValue/Builders.ts#L185), [CLKeyParameters](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/CLValue/Key.ts#L124).*

Converting the contract hash string above into any of these four types, and then into a `CLKey` using `CLValueBuilder.key(CLKeyParameters)` yields different errors, from the inability to unpack the deploy in the Casper Wallet to [empty arguments when deployed](https://testnet.cspr.live/deploy/0f37e519e1d64f330e9affc44a2c25c0bbe61493a989f2b67f2db5dc3593acde).

Here is my [attempted implementation](https://github.com/dylanireland/dApp-dev-series-8/blob/main/src/Deposit.js#L31).

My proposed solution is creating a new class `CLContractHash` and conforming it to `CLKeyParameters`.

**Comment by andrzej-casper** [comment]
I think it is doable - consider following `test.ts`:

```ts
import { CLAccountHash, CLValueBuilder } from "casper-js-sdk";

const accountHash = "fa5c933f908608377f451a52791b5d53955d99f7bad2707bd82eef32a893db5a"
const accountHashArr = Uint8Array.from(Buffer.from(accountHash, 'hex'));
const clAccountHash = new CLAccountHash(accountHashArr);
const key = CLValueBuilder.key(clAccountHash);

console.log("\nHere is CLKey:\n", key);
```

```
$ ts-node test.ts
@jsonMember on e.StoredValue: cannot resolve specified property constructor at runtime. If the type is not yet defined, for example due to circular references, add '() => ' before it. E.g. @jsonMember(() => Foo)

Here is CLKey:
 t {
  isCLValue: true,
  data: t {
    isCLValue: true,
    data: Uint8Array(32) [
      250, 92, 147,  63, 144, 134,   8,  55,
      127, 69,  26,  82, 121,  27,  93,  83,
      149, 93, 153, 247, 186, 210, 112, 123,
      216, 46, 239,  50, 168, 147, 219,  90
    ]
  }
}
````

**Comment by dylanireland** [comment]
Looking to get a contract hash here, or in the context of the VM, a "Hash" object. Following this pathway gives you an account hash which is typed as an `Account`. [see here](https://testnet.cspr.live/deploy/1b505443ce2f56a9644838c4b7dfc8f2afd6c3e025d737c6fcf30a4394fb0797).

Working on a `CLContractHash` implementation

**Comment by ghost** [comment]
Just looking how `CLKey` is parsed for contract hash:

https://github.com/casper-ecosystem/casper-js-sdk/blob/e217c4b0e6cb65f60d19db0ae1c25150d2cd2d00/src/lib/CLValue/Key.ts#L49-L57

The idea is that regular byte array is prefixed with _variant_ byte.

So as a workaround we can do it manually: 

```typescript
import { KeyVariant, CLByteArray, CLValueBuilder } from "casper-js-sdk";
import { concat } from '@ethersproject/bytes';

const contractHash = "cb781f66f78a398bf1709c4dac40b3cca17106824ea88ca9daa5b822421c9b57";
const clContractHash = new CLByteArray(
    concat([
        Uint8Array.from([KeyVariant.Hash]),
        Uint8Array.from(Buffer.from(contractHash, 'hex'))
    ])
);
const key = CLValueBuilder.key(clContractHash);
```

It works, but `CLContractHash` is definitely missing in the SDK.

**Comment by dylanireland** [comment]
Nice solution. In my case, adding `Uint8Array.from([KeyVariant.Hash])`  added **another** “01”. It appears to actually be as simple as:

```javascript
const clContractHash = new CLByteArray(Uint8Array.from(Buffer.from(contractHash, "hex")));
const key = CLValueBuilder.key(clContractHash);
```

I had previously tried this, but was using `TextEncoder` instead of `Buffer` because I was in a React environment, and `TextEncoder` assumed the text was UTF-8 not hex. Instead, for React, one can actually just use `decodeBase16` from [Conversions](https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/lib/Conversions.ts#L42) like so:

```javascript
import { decodeBase16, CLByteArray, CLValueBuilder } from "casper-js-sdk";

const contractHash = "cb781f66f78a398bf1709c4dac40b3cca17106824ea88ca9daa5b822421c9b57";
const clContractHash = new CLByteArray(decodeBase16(contractHash));
const key = CLValueBuilder.key(clContractHash);
```

Should still implement a `CLContractHash` though.

**Comment by hoffmannjan** [comment]
hey guys, yeah we will add `CLContractHash` in upcoming release !
