### ISSUE TITLE
Misleading function name

### ISSUE THREAD

**Issue by aurel-fr** [casper-ecosystem/casper-client-sdk#328]
**Describe the bug**
Misleading function name

**To Reproduce**

https://github.com/casper-ecosystem/casper-js-sdk/blob/53d7d9af15f4a2ffc33098490fa4b1cbe9de1cbb/src/lib/Keys.ts#L36

Expects a base64 key and not a base16 key, as the name would imply.

**Defect Type**
- [ ] Regression
- [ ] New
- [ ] Escape

**Comment by gyroflaw** [comment]
Yeah, the name should be `getKeysFromBase64PrivKey`

**Comment by alexmyshchyshyn** [comment]
📢 Notice: This issue is being closed as it is no longer relevant. We have completely rewritten the SDK, which renders this issue obsolete. If a similar concern arises in the new version, please feel free to open a new issue.

Thank you for your understanding. 🚀
