### ISSUE TITLE
Error loading transfer from JSON

### ISSUE THREAD

**Issue by meywood** [casper-ecosystem/casper-client-sdk#357]
**TypeError: Cannot read properties of undefined (reading 'toBytes')**
The following exception is thrown when reading the attached JSON:
[transfer.json.txt](https://github.com/casper-ecosystem/casper-js-sdk/files/12282033/transfer.json.txt)

**To Reproduce**
```
        const buf  = fs.readFileSync(`./src/json//transfer.json.`);
        expect(buf).to.not.be.undefined;
        // JavaScript SDK requires deploy prefix to attempt to deseirialise 
        const parsedJson: any = { deploy: JSON.parse(buf.toString()) };
        const transfer : Deploy = this.casperClient.deployFromJson(parsedJson).unwrap();
        expect(transfer).to.not.be.null;
        this.contextMap.put("transfer", transfer);
```

2.  ..

**Expected behavior**

**Screenshots**

**Additional context**

**Defect Type**
- [ ] Regression
- [ ] New
- [ ] Escape

**Comment by alexmyshchyshyn** [comment]
📢 Notice: This issue is being closed as it is no longer relevant. We have completely rewritten the SDK, which renders this issue obsolete. If a similar concern arises in the new version, please feel free to open a new issue.

Thank you for your understanding. 🚀
