### ISSUE TITLE
Setup tests in a way there will run both in mainnet and testnet env

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-client-sdk#360]
you can get the info from 

`curl -s -X POST --data-raw '{"jsonrpc": "2.0", "id": 1, "method": "info_get_status"}' -H 'Content-Type: application/json' https://rpc.mainnet.casperlabs.io/rpc | jq -r .result.build_version`
for mainnet 

`curl -s -X POST --data-raw '{"jsonrpc": "2.0", "id": 1, "method": "info_get_status"}' -H 'Content-Type: application/json' https://rpc.testnet.casperlabs.io/rpc | jq -r .result.build_version`
for testnet

please modify github actions scripts

**Comment by gyroflaw** [comment]
Mainnet
```bash
curl -s -X POST --data-raw '{"jsonrpc": "2.0", "id": 1, "method": "info_get_status"}' -H 'Content-Type: application/json' https://rpc.mainnet.casperlabs.io/rpc | jq -r .result.build_version | cut -d "-" -f 1
```

Testnet
```bash
curl -s -X POST --data-raw '{"jsonrpc": "2.0", "id": 1, "method": "info_get_status"}' -H 'Content-Type: application/json' https://rpc.testnet.casperlabs.io/rpc | jq -r .result.build_version | cut -d "-" -f 1
```
