### ISSUE TITLE
`queryContractData` Fails on AccountHash Value

### ISSUE THREAD

**Issue by dylanireland** [casper-ecosystem/casper-client-sdk#364]
**Describe the bug**

The `queryContractData` method in the [Contract class](https://github.com/casper-ecosystem/casper-js-sdk/blob/d05c540a06bca6b1d7fec340d8f9597c72918d79/src/lib/Contracts.ts#L136) fails when the value at the path is that of an Account Hash.

**To Reproduce**

Identify if any Prerequisites:

Have an arbitrary smart contract deployed to a Casper Network with a named key of type [`AccountHash`](https://docs.rs/casper-types/3.0.0/casper_types/account/struct.AccountHash.html).

Call the `queryContractData` function with the name of your named key as the path.

**Expected behavior**

The account hash should be parsed as a [`CLAccountHash`](https://github.com/casper-ecosystem/casper-js-sdk/blob/d05c540a06bca6b1d7fec340d8f9597c72918d79/src/lib/CLValue/AccountHash.ts#L46) (which is a `CLValue`) and returned.

**Example**

#### Smart Contract Side
```rust

#[no_mangle]
pub extern "C" fn call() {
  let owner = runtime::get_caller();

  let mut named_keys = NamedKeys::new();
  named_keys.insert(String::from("owner"), owner.into());
}
```
#### Casper JS SDK Side
```javascript

try {
  const owner = await contract.queryContractData(["owner"]);
} catch (error) {
  console.error(error.message); // throws: "Invalid stored value"
}

```

**Current Operating Workaround**
```javascript

const stateRootHashToUse = await client.nodeClient.getStateRootHash();

const owner = await client.nodeClient.getBlockState(
  stateRootHashToUse,
  CONTRACT_HASH,
  ["owner"]
);
console.log(owner);

```

produces:

```
e {
  Account: e {
    _accountHash: 'account-hash-aef7f03804a0f0bf0818aa1459eb0f1bd894a104e47f429bcfb55b5fc5d2cc84',
    namedKeys: [ [e], [e], [e] ],
    mainPurse: 'uref-209515c17782bd5cf78c08ddbdbe5cbc2aecce1737acbe8e7d1258a1a4b1e1fb-007',
    associatedKeys: [ [e] ],
    actionThresholds: e { deployment: 1, keyManagement: 1 }
  }
}
```

**Additional context**

Live smart contract with "owner" named key:

https://testnet.cspr.live/contract/962f8903632e77fa8db4dc78e21308f021dffbe7e6343703080caff80fd24d87

**Comment by gyroflaw** [comment]
@dylanireland thanks for detailed description.
After check the contract named keys, I found that you stored `owner` account hash directly which couldn't retrieve in the JS SDK.
![image](https://github.com/casper-ecosystem/casper-js-sdk/assets/83718263/01701f6b-8392-4fdc-a39b-7f17ec5894dd)

In your case

```ts
try {
  const owner = await contract.queryContractData(["owner"]);
} catch (error) {
  console.error(error.message); // throws: "Invalid stored value"
}
```
`owner` is [`AccountJson`](https://github.com/casper-ecosystem/casper-js-sdk/blob/9cd71d0194b78271a7689cb14e20db66a66c8b3f/src/lib/StoredValue.ts#L33) while the `queryContractData` method assumes the result should be [`CLValue`](https://github.com/casper-ecosystem/casper-js-sdk/blob/620c7c943e70b79359a604bcce945f50fddb38c7/src/lib/Contracts.ts#L153)

https://github.com/casper-ecosystem/casper-js-sdk/blob/620c7c943e70b79359a604bcce945f50fddb38c7/src/lib/Contracts.ts#L153-L157

AFAIK, to fetch the `owner` account hash, you should store like this

```rust

#[no_mangle]
pub extern "C" fn call() {
  let owner = runtime::get_caller();

  let mut named_keys = NamedKeys::new();
  let owner_key = storage::new_uref(owner).into();
  named_keys.insert(String::from("owner"), owner_key);
  ...
}
```
