### ISSUE TITLE
SPIKE - Review of PolkadotJS Endpoints

### ISSUE THREAD

**Issue by RBYGLLS** [casper-ecosystem/casper-client-sdk#366]
As per JSSDK 3.0  architecture discussions : https://github.com/casper-ecosystem/casper-js-sdk/discussions/332

**Comment by gyroflaw** [comment]
checking https://github.com/polkadot-js/api

**Comment by gyroflaw** [comment]
https://github.com/casper-ecosystem/casper-js-sdk/discussions/332#discussioncomment-7014067
