### ISSUE TITLE
 SPIKE - Review of Python SDK Endpoints

### ISSUE THREAD

**Issue by RBYGLLS** [casper-ecosystem/casper-client-sdk#367]
As per JSSDK 3.0  architecture discussions : https://github.com/casper-ecosystem/casper-js-sdk/discussions/332

Discussion Reference: https://github.com/casper-ecosystem/casper-js-sdk/discussions/332#discussioncomment-7096817

**Comment by gyroflaw** [comment]
https://github.com/casper-ecosystem/casper-js-sdk/discussions/332#discussioncomment-7096817
