### ISSUE TITLE
CLAnyType is missing CLAny value implementation

### ISSUE THREAD

**Issue by meywood** [casper-ecosystem/casper-client-sdk#382]
**Describe the bug**
It is not possible to construct or parse and CLAny value. The type definition for the Any type exists but there is not implementation of the Any value whose inner content will be a byte array.

**To Reproduce**

Identify if any Prequisites:

2.  ..

**Expected behavior**

**Screenshots**

**Additional context**

**Defect Type**
- [x] Regression
- [ ] New
- [ ] Escape

**Comment by gyroflaw** [comment]
Hello @meywood , thanks for raising this issue.
To implement your own CLType, you need to write 3 classes at least which extends `CLType`, `CLValueBytesParsers`, and `CLValue`.
Please check the examples [here](https://github.com/casper-ecosystem/casper-js-sdk/tree/dev/src/lib/CLValue).
[Here](https://gist.github.com/gyroflaw/fe63e8ff46016d15d3d3241e1dbfcbe7) is another example I wrote before.
