### ISSUE TITLE
NPM site does not contain latest version 2.15.3 codebase.

### ISSUE THREAD

**Issue by meywood** [casper-ecosystem/casper-client-sdk#383]
**Describe the bug**
https://www.npmjs.com/package/casper-js-sdk?activeTab=code does not have the correct code packaged and published for 2.15.3 look @ the query_balance method it is missing the StateIdentifier 

**To Reproduce**

Identify if any Prequisites:

2.  ..

**Expected behavior**

**Screenshots**

**Additional context**

**Defect Type**
- [ ] Regression
- [ ] New
- [ ] Escape

**Comment by hoffmannjan** [comment]
Hey @meywood you need to check the newest release branch not `dev` branch 
https://github.com/casper-ecosystem/casper-js-sdk/tree/release-2.15.3
