### ISSUE TITLE
`CasperServiceByJsonRPC.getStatus()` Error

### ISSUE THREAD

**Issue by dylanireland** [casper-ecosystem/casper-client-sdk#451]
**Describe the bug**
`CasperServiceByJsonRPC.getStatus()` returns the error: request for node status has failed: failed to deserialize a response: Deserialization error: early end of stream' on Condor

**To Reproduce**
Error observed on nctl running Condor (casper-node branch release-2.0.0-rc3).

1. Run Condor on nctl
2. 
```javascript
const service = new CasperServiceByJsonRPC("http://localhost:11101/rpc")
await service.getStatus()
```

**Defect Type**
- [ ] Regression
- [x] New
- [ ] Escape

**Comment by hoffmannjan** [comment]
Hm, are you running sidecar ? Asking because I tested it right now and it works for me. Please follow the [new `nctl` setup](https://github.com/casper-network/casper-nctl/blob/dev/docs/setup.md)

**Comment by hoffmannjan** [comment]
@dylanireland any updates from your side?

**Comment by alexmyshchyshyn** [comment]
📢 Notice: This issue is being closed as it is no longer relevant. We have completely rewritten the SDK, which renders this issue obsolete. If a similar concern arises in the new version, please feel free to open a new issue.

Thank you for your understanding. 🚀
