### ISSUE TITLE
Listen event bugs

### ISSUE THREAD

**Issue by norbubb** [casper-ecosystem/casper-client-sdk#457]
I use `https://mainnet.phantom-rpc.com/events/main` as sse url, follow the example to listen the Token transfer event, but it returns ```Event { type: 'error', message: undefined }``` error.

**Comment by ryoknz** [comment]
which version are you using?

**Comment by norbubb** [comment]
```
        "casper-cep18-js-client": "^1.0.3",
        "casper-js-sdk": "^2.15.6"

```

**Comment by norbubb** [comment]
@ryo-casper

**Comment by alexmyshchyshyn** [comment]
📢 Notice: We have completely rewritten the SDK, so you could try to use new SSE class.
All details could be found here: https://github.com/casper-ecosystem/casper-js-sdk/blob/feat-5.0.0/src/sse/README.md
 
If a similar concern arises in the new version, please feel free to open a new issue.
