### ISSUE TITLE
[Improvement] CLValue constructors for unsigned int are inconsistent

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-client-sdk#474]
U8 takes a number
U32 takes a BigNumber
U64 takes a BigNumberish
U128/256/512 takes a BigNumber or a string

**Comment by alexmyshchyshyn** [comment]
Hi @KillianH ,

Thank you for reporting the issue! 

- The **`CLValue`** constructors for unsigned integers have been updated to ensure consistency.

These fixes have been implemented and will be available in the upcoming release: **v5.0.0-beta2**.

If you have any further questions or feedback, feel free to reach out. Thanks for helping us improve! 🚀
